export const COMMENTS = {
  GET_COMMENTS: "GET_COMMENTS",
  GET_COMMENTS_SUCCESSFULL: "GET_COMMENTS_SUCCESSFULL",
  GET_COMMENTS_FAILED: "GET_COMMENTS_FAILED",
  DELETE_COMMENT: "DELETE_COMMENT",
  ADD_COMMENT: "ADD_COMMENT",
};
